/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside/index.vue')['default']
    ControllerContainer: typeof import('./src/components/NavBar/ControllerContainer.vue')['default']
    FullScreenSwitch: typeof import('./src/components/NavBar/FullScreenSwitch.vue')['default']
    LanguageChange: typeof import('./src/components/NavBar/LanguageChange.vue')['default']
    LayoutTitle: typeof import('./src/components/LayoutTitle/index.vue')['default']
    LocaleSwitch: typeof import('./src/components/NavBar/LocaleSwitch.vue')['default']
    MenuItem: typeof import('./src/components/Aside/MenuItem.vue')['default']
    MenuSwich: typeof import('./src/components/NavBar/MenuSwich.vue')['default']
    MenuSwitch: typeof import('./src/components/NavBar/MenuSwitch.vue')['default']
    MenuTitle: typeof import('./src/components/NavBar/MenuTitle.vue')['default']
    NavBar: typeof import('./src/components/NavBar/index.vue')['default']
    PanelContainer: typeof import('./src/components/PanelContainer/index.vue')['default']
    Permission: typeof import('./src/components/Permission/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Tag: typeof import('./src/components/TagViews/Tag.vue')['default']
    TagViews: typeof import('./src/components/TagViews/index.vue')['default']
    Test: typeof import('./src/components/test/index.vue')['default']
    ThemeSwitch: typeof import('./src/components/NavBar/ThemeSwitch.vue')['default']
    UserAvatar: typeof import('./src/components/NavBar/UserAvatar.vue')['default']
    UserAvater: typeof import('./src/components/NavBar/UserAvater.vue')['default']
  }
}
